set_property IOSTANDARD LVCMOS33 [get_ports Rst]
set_property PACKAGE_PIN N17 [get_ports Rst]
set_property IOSTANDARD LVCMOS33 [get_ports ClkIn]
set_property PACKAGE_PIN E3 [get_ports ClkIn]

set_property IOSTANDARD LVCMOS33 [get_ports L]
set_property PACKAGE_PIN V10 [get_ports L]
set_property IOSTANDARD LVCMOS33 [get_ports E]
set_property PACKAGE_PIN U11 [get_ports E]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property PACKAGE_PIN U12 [get_ports R]

set_property IOSTANDARD LVCMOS33 [get_ports L3]
set_property PACKAGE_PIN V17 [get_ports L3]
set_property IOSTANDARD LVCMOS33 [get_ports L2]
set_property PACKAGE_PIN R18 [get_ports L2]
set_property IOSTANDARD LVCMOS33 [get_ports L1]
set_property PACKAGE_PIN N14 [get_ports L1]
set_property IOSTANDARD LVCMOS33 [get_ports R1]
set_property PACKAGE_PIN J13 [get_ports R1]
set_property IOSTANDARD LVCMOS33 [get_ports R2]
set_property PACKAGE_PIN K15 [get_ports R2]
set_property IOSTANDARD LVCMOS33 [get_ports R3]
set_property PACKAGE_PIN H17 [get_ports R3]